trigger:
  - master
pool:
  vmImage: Ubuntu-16.04
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js
  - script: |
      npm install
      npm run build
      docker build -t $(dockerId).azurecr.io/$(imageName) .
      docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName)
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.9.1'
  - task: HelmDeploy@0
    inputs:
      connectionType: Azure Resource Manager
      azureSubscriptionEndpoint: 'Azure for Students(e9122c58-941a-4646-8e7c-aadf7be91202)'
      azureResourceGroup: $(azureResourceGroup)
      kubernetesCluster: $(kubernetesCluster)
      command: 'init'
