trigger:
  - master
pool:
  vmImage: Ubuntu-16.04
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js
  - script: |
      npm install
      npm run build
  - task: Docker@2
    inputs:
      containerRegistry: '71b33dea-988a-4d60-bd55-5b7bd4ad02d0'
      repository: 'dushantha/jamcam'
      command: 'buildAndPush'

  

