trigger:
  - master
pool:
  vmImage: Ubuntu-16.04
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js
  - script: |
      npm install
      npm run build
      docker build -t $(dockerId).azurecr.io/$(imageName) .
      docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName)
      key="jOiAp7bDAf4ok079E0yFDdKO1z+LBmuFOatj2bl1xwfWf2msQ+KGvALpM47CjeckKxnQo5giVhuchfy+BcamFQ==
"

